import { FuntunaImg } from "../assets/images";

export const allShares = [
  {
    title: "Sh-FUNTUNA",
    image: FuntunaImg,
    price: 10,
    hourProfit: 0.25,
    lifeSpan: 60,
    totalRevenue: 36,
  },
  {
    title: "Sh-FUNTUNA",
    image: FuntunaImg,
    price: 10,
    hourProfit: 0.25,
    lifeSpan: 60,
    totalRevenue: 36,
  },
  {
    title: "Sh-FUNTUNA",
    image: FuntunaImg,
    price: 10,
    hourProfit: 0.25,
    lifeSpan: 60,
    totalRevenue: 36,
  },
  {
    title: "Sh-FUNTUNA",
    image: FuntunaImg,
    price: 10,
    hourProfit: 0.25,
    lifeSpan: 60,
    totalRevenue: 36,
  },
  {
    title: "Sh-FUNTUNA",
    image: FuntunaImg,
    price: 10,
    hourProfit: 0.25,
    lifeSpan: 60,
    totalRevenue: 36,
  },
  {
    title: "Sh-FUNTUNA",
    image: FuntunaImg,
    price: 10,
    hourProfit: 0.25,
    lifeSpan: 60,
    totalRevenue: 36,
  },
  {
    title: "Sh-FUNTUNA",
    image: FuntunaImg,
    price: 10,
    hourProfit: 0.25,
    lifeSpan: 60,
    totalRevenue: 36,
  },
  {
    title: "Sh-FUNTUNA",
    image: FuntunaImg,
    price: 10,
    hourProfit: 0.25,
    lifeSpan: 60,
    totalRevenue: 36,
  },
  {
    title: "Sh-FUNTUNA",
    image: FuntunaImg,
    price: 10,
    hourProfit: 0.25,
    lifeSpan: 60,
    totalRevenue: 36,
  },
  {
    title: "Sh-FUNTUNA",
    image: FuntunaImg,
    price: 10,
    hourProfit: 0.25,
    lifeSpan: 60,
    totalRevenue: 36,
  },
  {
    title: "Sh-FUNTUNA",
    image: FuntunaImg,
    price: 10,
    hourProfit: 0.25,
    lifeSpan: 60,
    totalRevenue: 36,
  },
  {
    title: "Sh-FUNTUNA",
    image: FuntunaImg,
    price: 10,
    hourProfit: 0.25,
    lifeSpan: 60,
    totalRevenue: 36,
  },
];
